### ISSUE TITLE
Break Cluster detail view into separate views, update left nav

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak-explorer-gui#63]
As we add more functionality and capabilities to the Cluster detail view, it's starting to become too crowded.
Instead, let's have 3 sections for each Cluster, in the left nav:

```
production1
    Ops
    Data
    Query

localdev
    Ops
    Data
    Query

...
```

**Ops** is going to be the Cluster Operations / Stats / Cluster Management view. It'll house the list of nodes (with links to their effective configs, stats, etc). And this is where we'll be putting the graphs and cluster-wide statistics. 

**Data** will house the current data exploration functionality (list of bucket types, etc).

**Query** is a place for Search-related (and later on, 2i-related) functionality. So, move the indexes and schemas to there. Also, this is where we'll put a search box / query builder functionality.

**Comment by paultannenbaum** [comment]
I still have to update the breadcrumb component, but I wanted to get your opinion on this:

<img width="1440" alt="screenshot 2015-12-22 10 31 34" src="https://cloud.githubusercontent.com/assets/220885/11962780/5b5434cc-a897-11e5-95dc-e886c76bf3d7.png">

I wonder if this is putting too much information in the left sidebar? Maybe there is a better way to represent the three distinct sections than having each cluster have three sub links in the sidebar. Another possibility would be leaving the sidebar the same but moving each section to its own panel in a tabbed layout, like how nodes have stats and configurations. Here is the branch if you want to pull it down and test it against your local data:

https://github.com/basho-labs/riak-explorer-gui/tree/left-nav-update

**Comment by dmitrizagidulin** [comment]
I see what you're saying, about having to think carefully here. Part of the unknown here is - how many clusters will people typically use this for? My current guess is - not more than 1-4, since production cluster security will dictate that Explorer be either inside the prod cluster's network, or have a separate Admin profile. It remains to be seen, from the field.

My gut feel is to lean away from tabs, since they're not as easily discoverable by just glancing at the navbar. 

What do you think about possibly lining up the links horizontally? Sort of like:

```
cluster1
    Ops | Data | Query

cluster2
    Ops | Data | Query
```

If you don't mind, don't capitalize the cluster ids on the nav bar, either, since those are case sensitive.

**Comment by paultannenbaum** [comment]
So here is an updated styled left navigation, using the suggested changes:
<img width="1440" alt="screenshot 2015-12-28 09 18 37" src="https://cloud.githubusercontent.com/assets/220885/12022366/06852cb0-ad44-11e5-9f7e-18ade0c5fb3d.png">

I think it is much better than my first attempt at it, but I still feel putting this much navigational state in the left nav is not very intuitive. At the end of the day the user just has to learn this lesson once and then they understand, but I am skeptical this is the best approach. 

On top of just UX concerns, there are technical concerns as well. I would assume we would want to store a "selected" state on the given sub cluster section (i.e foo-cluster/ops). Because there are states that do not fall within these at all (help page, root page, etc), we will have to implement some kind of mechanism at the root application level that on every route change will decide whether or not it is within a cluster section, and if so set the appropriate selected class on the sidebar element. Nothing too crazy, but it is worth considering that this story is adding additional technical complexity to the project as well. 

I personally would vote for punting this story until the rest of the V1 features are in place, and then doing a more thorough UX examination at that point.

**Comment by dmitrizagidulin** [comment]
Can you explain more, about which parts are not intuitive? 

In general, I think we should move ahead with the sections, but punt on the part where we show the selected state.

**Comment by paultannenbaum** [comment]
Updated screenshots:
<img width="1440" alt="screenshot 2015-12-30 12 40 39" src="https://cloud.githubusercontent.com/assets/220885/12057213/65feb73c-aef3-11e5-844d-0cf6555c6d91.png">
<img width="1440" alt="screenshot 2015-12-30 12 43 29" src="https://cloud.githubusercontent.com/assets/220885/12057214/67b138f2-aef3-11e5-8b83-3dc4f70a753b.png">
